name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]
  
jobs:
  tag-match:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - tag-match: '\d{1,3}.\d{1,3}.\d{1,3}'
            tag-match-group: '0'
          - tag-match: '\d{1,3}.\d{1,3}'
            tag-match-group: '0'
          - tag-match: 'v(.*)'
            tag-match-group: '1'
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker Meta
      id: docker_meta
      uses: ./
      with:
        images: ${{ env.DOCKER_IMAGE }} # list of Docker images to use as base name for tags
        tag-sha: true
        tag-match: '\d{1,3}.\d{1,3}.\d{1,3}'
    - name: Build and push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tgrymnak/watchdocker
        tags: ${{ steps.docker_meta.outputs.tags }}
