name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]
  
jobs:
  docker:
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    include:
    #      - tag-match: 'master'
    #        tag-match-group: '0'
    #      - tag-match: '\d{1,3}.\d{1,3}.\d{1,3}'
    #        tag-match-group: '1'
    steps:
    - name: Set image version
      id: image_version
      run: |
          echo ::set-output name=IMAGE_VERSION::${GITHUB_REF#refs/*/}
    #- name: Docker metadata
    #  id: docker_meta
    #  uses: crazy-max/ghaction-docker-meta@v1
    #  with:
    #    images: tgrymnak/watchdocker
    #    tag-match: ${{ matrix.tag-match }}
    #    tag-match-group: ${{ matrix.tag-match-group }}
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        #push: true
        tags: ${{ steps.image_version.IMAGE_VERSION }}
