name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - v*.*.*
  pull_request:
    branches: [ master ]
  
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build and push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: tgrymnak/watchdocker
        tags: $VERSION_TAG
