name: Docker Image CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]
  
jobs:
  docker:
    runs-on: ubuntu-latest
    #strategy:
    #  fail-fast: false
    #  matrix:
    #    include:
    #      - tag-match: 'master'
    #        tag-match-group: '0'
    #      - tag-match: '\d{1,3}.\d{1,3}.\d{1,3}'
    #        tag-match-group: '1'
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Docker metadata
      id: docker_meta
      uses: crazy-max/ghaction-docker-meta@v1
      with:
        images: tgrymnak/watchdocker

    #- name: Extract tag name
    #  id: tag
    #  run: |
    #      # Strip git ref prefix from version
    #      VERSION=${{ steps.docker_meta.outputs.tags }}
    #      # Use Docker `latest` tag convention
    #      [ "$VERSION" == "master" ] && VERSION=latest
    #      echo ::set-output name=IMAGE_VERSION::$VERSION
    #- name: Get image version
    #  id: image_version
    #  run: |
    #    echo ${{ steps.tag.outputs.IMAGE_VERSION }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to Docker Hub
      uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
    - name: Build and push to Docker Hub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
